/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.simple.app.vistas.custom;

import com.simple.app.vistas.interfaces.TableActionEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lynkos
 */
public class OptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionPanel
     */
    public OptionPanel() {
        initComponents();
    }
    
    
    public void initEvent(TableActionEvent event, int row) {
        btnEditar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        btnEliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new com.simple.app.vistas.custom.ActionButton();
        btnEliminar = new com.simple.app.vistas.custom.ActionButton();

        setLayout(new java.awt.GridBagLayout());

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        add(btnEditar, new java.awt.GridBagConstraints());

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        add(btnEliminar, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.simple.app.vistas.custom.ActionButton btnEditar;
    private com.simple.app.vistas.custom.ActionButton btnEliminar;
    // End of variables declaration//GEN-END:variables
}
