/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.simple.app.vistas.dialogs;

import com.simple.app.dao.ClienteJpaController;
import com.simple.app.modelo.Cliente;
import java.util.List;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lynkos
 */
public class BuscarClienteDialog extends javax.swing.JDialog {

    /**
     * Creates new form BuscarCliente
     */
    
    private Cliente clienteSeleccionado = new Cliente();
    public BuscarClienteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTablaClientes(null);
        handlerListSeleccion();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        rbCedula = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbApellido = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCedula);
        rbCedula.setSelected(true);
        rbCedula.setText("DNI/CEDULA");

        buttonGroup1.add(rbNombre);
        rbNombre.setText("Nombre");

        buttonGroup1.add(rbApellido);
        rbApellido.setText("Apellido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbCedula)
                        .addGap(18, 18, 18)
                        .addComponent(rbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbApellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCliente)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCedula)
                    .addComponent(rbNombre)
                    .addComponent(rbApellido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setEnabled(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSeleccionar, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        
        List<Cliente> listaClientes = null;
        
        if(rbCedula.isSelected()){
            listaClientes = this.obtenerListaClientesCedula(this.txtCliente.getText());            
        }else if(rbNombre.isSelected()){
            listaClientes = this.obtenerListaClientesNombre(this.txtCliente.getText());
        }else if(rbApellido.isSelected()){
            listaClientes = this.obtenerListaClientesApellido(this.txtCliente.getText());
        }
        this.cargarTablaClientes(listaClientes);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

public void cargarTablaClientes(List<Cliente> listaClientesParam){
   
        List<Cliente> listaClientes = listaClientesParam;
        if(listaClientesParam == null){
            listaClientes = obtenerListaClientes();
        }  
        
        if(listaClientes == null || listaClientes.isEmpty()){
            return;
        }        
        
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        this.tblClientes = new JTable(defaultTableModel);
        this.jScrollPane1.setViewportView(this.tblClientes);
        
        defaultTableModel.addColumn("idCliente");
        defaultTableModel.addColumn("Nombre");
        defaultTableModel.addColumn("Apellido");
        defaultTableModel.addColumn("Cedula/DNI");
        defaultTableModel.addColumn("Telefono");
        defaultTableModel.addColumn("Direccion");
        defaultTableModel.addColumn("Estado");        
        
        listaClientes.forEach((Cliente cliente) -> {
            
            Object fila[] = new Object[8];
            fila[0] = cliente.getIdCliente();
            fila[1] = cliente.getNombre();
            fila[2] = cliente.getApellido();
            fila[3] = cliente.getCedula();
            fila[4] = cliente.getTelefono();
            fila[5] = cliente.getDireccion();
            fila[6] = cliente.getEstado();

            defaultTableModel.addRow(fila);
            
        });        
}

private void handlerListSeleccion(){
    this.tblClientes.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent e) {
            int idCliente = (Integer)tblClientes.getValueAt(tblClientes.getSelectedRow(), 0);
            clienteSeleccionado = obtenerListaClientes(idCliente);
            btnSeleccionar.setEnabled(true);
        }
    
    });
}

private List<Cliente> obtenerListaClientes(){
    ClienteJpaController clienteJpaController = new ClienteJpaController();
    List<Cliente> listaClientes = clienteJpaController.findClienteEntities();
    clienteJpaController.close();
    return listaClientes;
}

private List<Cliente> obtenerListaClientesCedula(String data){
    ClienteJpaController clienteJpaController = new ClienteJpaController();
    List<Cliente> listaClientes = clienteJpaController.findClientesByOptions(data, "cedula");
    clienteJpaController.close();
    return listaClientes;
}

private List<Cliente> obtenerListaClientesNombre(String data){
    ClienteJpaController clienteJpaController = new ClienteJpaController();
    List<Cliente> listaClientes = clienteJpaController.findClientesByOptions(data, "nombre");
    clienteJpaController.close();
    return listaClientes;
}

private List<Cliente> obtenerListaClientesApellido(String data){
    ClienteJpaController clienteJpaController = new ClienteJpaController();
    List<Cliente> listaClientes = clienteJpaController.findClientesByOptions(data, "apellido");
    clienteJpaController.close();
    return listaClientes;
}


private Cliente obtenerListaClientes(int idCliente){
    ClienteJpaController clienteJpaController = new ClienteJpaController();
    Cliente cliente = clienteJpaController.findCliente(idCliente);
    clienteJpaController.close();
    return cliente;
}


public Cliente getClienteSeleccionado(){
    return this.clienteSeleccionado;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbApellido;
    private javax.swing.JRadioButton rbCedula;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
