/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.simple.app.vistas;

import com.simple.app.dao.ClienteJpaController;
import com.simple.app.modelo.Cliente;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lynkos
 */
public class IFFacturacion extends javax.swing.JInternalFrame {

    
    private Cliente clienteSeleccionado = null;
    
    /**
     * Creates new form IFFacturacion
     */
    public IFFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgOpcionesBusquedaCliente = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rbOpcionNombre = new javax.swing.JRadioButton();
        rbOpcionApellido = new javax.swing.JRadioButton();
        rbOpcionDni = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtNombreProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar cliente"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new java.awt.GridBagLayout());

        txtCedula.setPreferredSize(new java.awt.Dimension(160, 22));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel5.add(txtCedula, gridBagConstraints);

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel5.add(btnBuscarCliente, gridBagConstraints);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar cliente por"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        bgOpcionesBusquedaCliente.add(rbOpcionNombre);
        rbOpcionNombre.setText("Nombre");
        jPanel6.add(rbOpcionNombre);

        bgOpcionesBusquedaCliente.add(rbOpcionApellido);
        rbOpcionApellido.setText("Apellido");
        jPanel6.add(rbOpcionApellido);

        bgOpcionesBusquedaCliente.add(rbOpcionDni);
        rbOpcionDni.setSelected(true);
        rbOpcionDni.setText("Cedula/DNI");
        rbOpcionDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcionDniActionPerformed(evt);
            }
        });
        jPanel6.add(rbOpcionDni);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar producto"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setLayout(new java.awt.GridBagLayout());

        txtNombreProducto.setMinimumSize(new java.awt.Dimension(180, 22));
        txtNombreProducto.setPreferredSize(new java.awt.Dimension(180, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 4);
        jPanel7.add(txtNombreProducto, gridBagConstraints);

        btnBuscarProducto.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel7.add(btnBuscarProducto, gridBagConstraints);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Costos"));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Subtotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Descuento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Impuestos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Efectivo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Cambio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel6, gridBagConstraints);

        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jFormattedTextField1, gridBagConstraints);

        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jFormattedTextField2, gridBagConstraints);

        jFormattedTextField3.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jFormattedTextField3, gridBagConstraints);

        jFormattedTextField4.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jFormattedTextField4, gridBagConstraints);

        jFormattedTextField5.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jFormattedTextField5, gridBagConstraints);

        jFormattedTextField6.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jFormattedTextField6, gridBagConstraints);

        jButton1.setText("Registrar venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel9.add(jButton1, gridBagConstraints);

        jButton2.setText("Calcular cambio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel9.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel9);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
       
        if(this.txtCedula.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Ingrese una Cedula/DNI");
            return;
        }
        createPopupClientes(this.txtCedula.getText().trim());
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void rbOpcionDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcionDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcionDniActionPerformed

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {

        if (this.txtCedula.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Cedula/DNI");
            return;
        }
        createPopupClientes(this.txtCedula.getText().trim());
    }
    
    
    
    private void createPopupClientes(String data) {
        // Create the table model and JTable
        String[] columnNames = {"Nombre", "Apellido", "Cedula/DNI"};
        ClienteJpaController clienteJpaController = new ClienteJpaController();
        List<Cliente> listaClientes = clienteJpaController.findClientesByOptions(data, "cedula");
        if(listaClientes == null) {
            JOptionPane.showMessageDialog(null, "Sin resultados");
            return;
        }

        if(listaClientes.size() == 0) {
            JOptionPane.showMessageDialog(null, "Sin resultados");
            return;
        }       
        
        Object[][] rowData = new Object[listaClientes.size()][3];
        
        for(int i = 0; i< listaClientes.size(); i++){
            rowData[i] = new Object[]{
                                       listaClientes.get(i).getNombre(), 
                                       listaClientes.get(i).getApellido(), 
                                       listaClientes.get(i).getCedula()
                                     };
        }

        
                // Create the popup window
        JDialog popup = new JDialog((JFrame) null, "Seleccionar Cliente", true);
        DefaultTableModel tableModel = new DefaultTableModel(rowData, columnNames);        
        JTable table = new JTable(tableModel);
       JButton btnSeleccionar = new JButton("Seleccionar Cliente");
       btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int filaSeleccionada = table.getSelectedRow();
                if(filaSeleccionada >= 0){
                    clienteSeleccionado =  listaClientes.get(filaSeleccionada);
                    popup.dispose();
                }                                
            }
        }
       );
       

        // Add the JTable to a JScrollPane
        JScrollPane scrollPane = new JScrollPane(table);

        // Create the main content panel and add the scroll pane
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(scrollPane, BorderLayout.CENTER);
        contentPanel.add(btnSeleccionar, BorderLayout.PAGE_END);


        popup.setContentPane(contentPanel);
        popup.pack();
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
        System.out.println("................Proceso Termiando: "+clienteSeleccionado.getNombre());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcionesBusquedaCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbOpcionApellido;
    private javax.swing.JRadioButton rbOpcionDni;
    private javax.swing.JRadioButton rbOpcionNombre;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
