/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.simple.app.vistas;

import com.simple.app.dao.ClienteJpaController;
import com.simple.app.dao.ProductoJpaController;
import com.simple.app.modelo.Cliente;
import com.simple.app.modelo.DetalleVenta;
import com.simple.app.modelo.Producto;
import com.simple.app.vistas.models.DetalleVentaTableModel;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lynkos
 */
public class IFFacturacion extends javax.swing.JInternalFrame {

    
    private Cliente clienteSeleccionado = null;
    private List<Producto> listaProductosSelecionados;
    private List<DetalleVenta> listaDetalleVentas;
    private DetalleVentaTableModel detalleVentaTableModel;
    
    /**
     * Creates new form IFFacturacion
     */
    public IFFacturacion() {
        this.setSize(600, 800);
        initComponents();
        this.listaProductosSelecionados = new ArrayList<>();
        this.listaDetalleVentas = new ArrayList<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgOpcionesBusquedaCliente = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rbOpcionNombre = new javax.swing.JRadioButton();
        rbOpcionApellido = new javax.swing.JRadioButton();
        rbOpcionDni = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtNombreProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleVentas = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jftSubtotal = new javax.swing.JFormattedTextField();
        jftDescuento = new javax.swing.JFormattedTextField();
        jftImpuestos = new javax.swing.JFormattedTextField();
        jftTotal = new javax.swing.JFormattedTextField();
        jftEfectivo = new javax.swing.JFormattedTextField();
        jftCambio = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombreClienteVista = new javax.swing.JTextField();
        txtCedulaClienteVista = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar cliente"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new java.awt.GridBagLayout());

        txtCedula.setPreferredSize(new java.awt.Dimension(160, 22));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel5.add(txtCedula, gridBagConstraints);

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel5.add(btnBuscarCliente, gridBagConstraints);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar cliente por"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        bgOpcionesBusquedaCliente.add(rbOpcionNombre);
        rbOpcionNombre.setText("Nombre");
        jPanel6.add(rbOpcionNombre);

        bgOpcionesBusquedaCliente.add(rbOpcionApellido);
        rbOpcionApellido.setText("Apellido");
        jPanel6.add(rbOpcionApellido);

        bgOpcionesBusquedaCliente.add(rbOpcionDni);
        rbOpcionDni.setSelected(true);
        rbOpcionDni.setText("Cedula/DNI");
        rbOpcionDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcionDniActionPerformed(evt);
            }
        });
        jPanel6.add(rbOpcionDni);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar producto"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setLayout(new java.awt.GridBagLayout());

        txtNombreProducto.setMinimumSize(new java.awt.Dimension(180, 22));
        txtNombreProducto.setPreferredSize(new java.awt.Dimension(180, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 4);
        jPanel7.add(txtNombreProducto, gridBagConstraints);

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel7.add(btnBuscarProducto, gridBagConstraints);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        tblDetalleVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "Nombre", "Cantidad", "P. Unitario", "Subtotal", "Descuento", "Impuesto", "Total a pagar", "Accion"
            }
        ));
        jScrollPane1.setViewportView(tblDetalleVentas);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Costos"));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Subtotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Descuento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Impuestos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Efectivo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Cambio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        jPanel9.add(jLabel6, gridBagConstraints);

        jftSubtotal.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jftSubtotal, gridBagConstraints);

        jftDescuento.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jftDescuento, gridBagConstraints);

        jftImpuestos.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jftImpuestos, gridBagConstraints);

        jftTotal.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jftTotal, gridBagConstraints);

        jftEfectivo.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jftEfectivo, gridBagConstraints);

        jftCambio.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 6);
        jPanel9.add(jftCambio, gridBagConstraints);

        jButton1.setText("Registrar venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel9.add(jButton1, gridBagConstraints);

        jButton2.setText("Calcular cambio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel9.add(jButton2, gridBagConstraints);

        jLabel7.setText("Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 45, 6);
        jPanel9.add(jLabel7, gridBagConstraints);

        txtNombreClienteVista.setEditable(false);
        txtNombreClienteVista.setEnabled(false);
        txtNombreClienteVista.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 45, 5);
        jPanel9.add(txtNombreClienteVista, gridBagConstraints);

        txtCedulaClienteVista.setEditable(false);
        txtCedulaClienteVista.setEnabled(false);
        txtCedulaClienteVista.setMinimumSize(new java.awt.Dimension(120, 22));
        txtCedulaClienteVista.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 45, 5);
        jPanel9.add(txtCedulaClienteVista, gridBagConstraints);

        getContentPane().add(jPanel9);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
       
        if(this.txtCedula.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Ingrese una Cedula/DNI");
            return;
        }
        
        if(this.rbOpcionApellido.isSelected()){
            
            createPopupClientes(this.txtCedula.getText().trim(), "apellido");
        }else if(this.rbOpcionNombre.isSelected()){
            
            createPopupClientes(this.txtCedula.getText().trim(), "nombre");
            
        }else{
            createPopupClientes(this.txtCedula.getText().trim(), "cedula");
        }
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void rbOpcionDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcionDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcionDniActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        if(this.txtNombreProducto.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Ingrese nombre de producto.");
            return;
        }
        createPopupProductos(this.txtNombreProducto.getText());
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    
    
    
    private void createPopupClientes(String data,String opcion) {
        // Create the table model and JTable
        String[] columnNames = {"Nombre", "Apellido", "Cedula/DNI"};
        ClienteJpaController clienteJpaController = new ClienteJpaController();
        List<Cliente> listaClientes = clienteJpaController.findClientesByOptions(data, opcion);
        if(listaClientes == null) {
            JOptionPane.showMessageDialog(null, "Sin resultados");
            return;
        }

        if(listaClientes.size() == 0) {
            JOptionPane.showMessageDialog(null, "Sin resultados");
            return;
        }       
        
        Object[][] rowData = new Object[listaClientes.size()][3];
        
        for(int i = 0; i< listaClientes.size(); i++){
            rowData[i] = new Object[]{
                                       listaClientes.get(i).getNombre(), 
                                       listaClientes.get(i).getApellido(), 
                                       listaClientes.get(i).getCedula()
                                     };
        }

        
                // Create the popup window
        JDialog popup = new JDialog((JFrame) null, "Seleccionar Cliente", true);
        DefaultTableModel tableModel = new DefaultTableModel(rowData, columnNames);        
        JTable table = new JTable(tableModel);
       JButton btnSeleccionar = new JButton("Seleccionar Cliente");
       btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int filaSeleccionada = table.getSelectedRow();
                if(filaSeleccionada >= 0){
                    clienteSeleccionado =  listaClientes.get(filaSeleccionada);
                    txtNombreClienteVista.setText(clienteSeleccionado.getNombre());
                    txtCedulaClienteVista.setText(clienteSeleccionado.getCedula());
                    popup.dispose();
                }                                
            }
        }
       );
       

        // Add the JTable to a JScrollPane
        JScrollPane scrollPane = new JScrollPane(table);

        // Create the main content panel and add the scroll pane
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(scrollPane, BorderLayout.CENTER);
        contentPanel.add(btnSeleccionar, BorderLayout.PAGE_END);


        popup.setContentPane(contentPanel);
        popup.pack();
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
        //System.out.println("................Proceso Termiando: "+clienteSeleccionado.getNombre());
    }
    
    
    private void createPopupProductos(String nombreProducto) {
        // Create the table model and JTable
        String[] columnNames = {"Nombre", "Precio","Stock" ,"Ingrese Cantidad"};
        ProductoJpaController productoJpaController = new ProductoJpaController();
        List<Producto> listaProducto = productoJpaController.findProductosByName(nombreProducto);
        if (listaProducto == null) {
            JOptionPane.showMessageDialog(null, "Sin resultados");
            return;
        }

        if (listaProducto.size() == 0) {
            JOptionPane.showMessageDialog(null, "Sin resultados");
            return;
        }
        
        Object[][] rowData = new Object[listaProducto.size()][4];

        for (int i = 0; i < listaProducto.size(); i++) {
            rowData[i] = new Object[]{
                listaProducto.get(i).getNombre(),
                listaProducto.get(i).getPrecio(),
                listaProducto.get(i).getCantidad(),
                1
            };
        }

        // Create the popup window
        JDialog popup = new JDialog((JFrame) null, "Seleccionar Producto", true);
        DefaultTableModel tableModel = new DefaultTableModel(rowData, columnNames);
        JTable table = new JTable(tableModel);
        JButton btnSeleccionar = new JButton("Seleccionar Producto");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int filaSeleccionada = table.getSelectedRow();
                if (filaSeleccionada >= 0) {
                    Producto productoSelecionado = listaProducto.get(filaSeleccionada);
                    String cantidadString = table.getValueAt(filaSeleccionada, 3).toString();
                    int cantidadNumerica = 1;
                    try{
                        cantidadNumerica = Integer.parseInt(cantidadString);
                        if(cantidadNumerica > productoSelecionado.getCantidad()){
                            JOptionPane.showMessageDialog(null, "La cantidad Ingresada supera el stock actual.");
                            return;
                        }
                    }catch(HeadlessException | NumberFormatException e){
                        System.out.println(e.getMessage());
                        cantidadNumerica = 1;
                    }
                    boolean yaFueAgregado = listaProductosSelecionados.stream().anyMatch(prd -> {
                        return prd.getIdProducto() == productoSelecionado.getIdProducto();
                    });
                    
                    if(yaFueAgregado){
                        JOptionPane.showMessageDialog(null, "Este producto ya fue agregado.");
                        return;
                    }
                    generarDetalleVenta(productoSelecionado, cantidadNumerica);
                    popup.dispose();
                }
            }
        }
        );

        // Add the JTable to a JScrollPane
        JScrollPane scrollPane = new JScrollPane(table);

        // Create the main content panel and add the scroll pane
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(scrollPane, BorderLayout.CENTER);
        contentPanel.add(btnSeleccionar, BorderLayout.PAGE_END);

        popup.setContentPane(contentPanel);
        popup.pack();
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
        //System.out.println("................Proceso Termiando: "+clienteSeleccionado.getNombre());
    }
    
    private void generarDetalleVenta(Producto producto, int cantidad){
        listaProductosSelecionados.add(producto); 
        
        double descuento = 0.0;
        double iva_impuesto = (producto.getPrecio() * cantidad) * producto.getPorcentajeIva();
        double subtotal = producto.getPrecio() * cantidad;
        double totalPagar = subtotal + iva_impuesto + descuento;

        //redondear decimales
        subtotal = (double) Math.round(subtotal * 100) / 100;
        double iva = (double) Math.round(iva_impuesto * 100) / 100;
        descuento = (double) Math.round(descuento * 100) / 100;
        totalPagar = (double) Math.round(totalPagar * 100) / 100;
        
        DetalleVenta detalleVenta = new DetalleVenta();
        detalleVenta.setIdCabeceraVenta(1);
        detalleVenta.setIdProducto(producto.getIdProducto());
        detalleVenta.setCantidad(cantidad);
        detalleVenta.setPrecioUnitario(producto.getPrecio());
        detalleVenta.setSubTotal(subtotal);
        detalleVenta.setDescuento(descuento);
        detalleVenta.setIva(iva);
        detalleVenta.setTotalPagar(totalPagar);
        detalleVenta.setEstado(1);
        
        this.listaDetalleVentas.add(detalleVenta);
        this.listaProductosSelecionados.add(producto);
        this.calcularPagoFinal(this.listaDetalleVentas);
        
        this.detalleVentaTableModel = new DetalleVentaTableModel(listaDetalleVentas, listaProductosSelecionados);
        this.tblDetalleVentas.setModel(detalleVentaTableModel);
        
        
    }
    
    private void calcularPagoFinal(List<DetalleVenta> detallesVentas){
        
        double  totalPagar = 0.0;
         double descuento = 0.0;
        double iva_impuesto = 0.0;
        double subtotal = 0.0;
        
        for(DetalleVenta detalleVenta: detallesVentas ){
            totalPagar += detalleVenta.getTotalPagar();
            descuento += detalleVenta.getDescuento();
            iva_impuesto += detalleVenta.getIva();
            subtotal += detalleVenta.getSubTotal();
        }
        
        this.jftSubtotal.setValue(subtotal);
        this.jftDescuento.setValue(descuento);
        this.jftImpuestos.setValue(iva_impuesto);
        this.jftTotal.setValue(totalPagar);
        
    }    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcionesBusquedaCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jftCambio;
    private javax.swing.JFormattedTextField jftDescuento;
    private javax.swing.JFormattedTextField jftEfectivo;
    private javax.swing.JFormattedTextField jftImpuestos;
    private javax.swing.JFormattedTextField jftSubtotal;
    private javax.swing.JFormattedTextField jftTotal;
    private javax.swing.JRadioButton rbOpcionApellido;
    private javax.swing.JRadioButton rbOpcionDni;
    private javax.swing.JRadioButton rbOpcionNombre;
    private javax.swing.JTable tblDetalleVentas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaClienteVista;
    private javax.swing.JTextField txtNombreClienteVista;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
